<?php

namespace Varas\Euler;

/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
class Problem2
{
    public function getTitle()
    {
        return __CLASS__;
    }

    public function getSolution()
    {
        return $this->solve(4000000);
    }

    public function solve($givenNumber)
    {
        $numbers = range(1,$givenNumber);
        $fibonacciTerms = array_map('Varas\Math\fibonacci', $numbers);
        $fibonacciTermsEvenValued = array_filter($fibonacciTerms, 'Varas\Math\evenValued');
        return array_reduce($fibonacciTermsEvenValued, 'Varas\Math\add');
    }
}
